#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sun Oct 30 21:30:42 2016

@author: tfalcoff
"""
import urllib
from html2text import html2text
import requests

r = requests.get('http://moviebodycounts.com/Braveheart.htm')

print(html2text(r.text))



