#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Fri Nov 11 00:45:52 2016

@author: tfalcoff
"""
from bs4 import BeautifulSoup
import requests, string


class spyware:
    
    
    def __init__(self, url):
        
        page = requests.get(url).text
        soup = BeautifulSoup(page, 'lxml')

        n_title = ''
        for char in soup.title:
            if char in string.punctuation:
                char = ' '
            n_title += char
            
        l_title = n_title.split(' ')

        l_title = l_title[:-2]
            
        title = '_'.join(l_title)
        
        links=[]
        [links.append(link['href']) for link in soup.find_all('a', href=True)]
        fin_links=[]
        for link in links:
            if link[:6] == '/wiki/' and ':' not in link:
                if 'Main_Page' not in link and link[6:] != title:
                    fin_links.append(link)
        
        self.links = fin_links
        
    
    def links(self):
        
        return self.links
                    
        